---

- name: Ensure the standard locale exists
  community.general.locale_gen:
    name: "{{ standard_locale }}"
    state: present

- name: Change hostname to FQDN
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  ignore_errors: true

- name: Add the ansible user "ansible" with a bash shell, appending the group 'sudo' to the user's groups
  ansible.builtin.user:
    name: ansible
    password: "{{ ansible_pwd | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Make sure line is in /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^ansible '
    line: "ansible    ALL = (ALL) NOPASSWD: ALL"

#- name: sshd_config

...
